# Generated by Django 4.2.17 on 2025-01-20 16:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0002_userprofile_date_joined_userprofile_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_recipes',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
