# Generated by Django 4.2.20 on 2025-04-26 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(choices=[('appetizer', 'Appetizer'), ('main_course', 'Main Course'), ('dessert', 'Dessert'), ('beverage', 'Beverage'), ('snack', 'Snack')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.category'),
        ),
    ]
